services:
  app:
    container_name: pokenary_app
    build:
      context: ./
      dockerfile: ./docker/pokenary/Dockerfile
    volumes:
      - .:/pokenary
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 2048M
    command: python manage.py runserver 0.0.0.0:8000
  db:
    container_name: pokenary_db
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    image: mysql:latest
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_pokenary_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'pokenary'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    deploy:
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 2048M
volumes:
  mysql_pokenary_data: