version: "3"
services:
  app:
    build: .
    volumes:
      - .:/pokenary
    ports:
      - 8000:8000
    image: app:pokenary
    container_name: pokenary_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: mysql:latest
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'pokenary'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    container_name: mysql_db