# Generated by Django 4.0.3 on 2022-05-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='abilities',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evolutions',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='moves',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
