# Generated by Django 4.0.3 on 2022-05-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_pokemon_moves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='abilities',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='evolutions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='moves',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='types',
            field=models.TextField(),
        ),
    ]
