# Generated by Django 4.0.3 on 2022-05-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='pokemon',
            new_name='pokemon_id',
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='user',
            new_name='user_id',
        ),
    ]
