# Generated by Django 4.0.3 on 2022-05-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_pokemon_favorites_pokemon_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='pokemon_id',
            new_name='pokemon',
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='user_id',
            new_name='user',
        ),
    ]
