# Generated by Django 4.0.3 on 2022-05-27 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_pokemon_id_favorites_pokemon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='stars',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
